In [1]:
import pandas as pd
import numpy as np

In [39]:
# read data

dir = 'C:/Users/jesse/OneDrive/Documents/Multiplex Lab/Data/Final Combined.xlsx'

df = pd.read_excel(dir)

In [3]:
df

,1 cell,CD8a,CD4,CD25,CD27,CD28,CD45,CD69,CD45RA,CD38,...,ARF6,cofilin,Cathepsin B,NFAT,IkB-alpha,TBK1,SHP2,NOL3,ROCK1,PKC alpha
0,1,1017.5,1004.5,1023.5,1020.5,989.0,1014.0,1011.0,1030.0,1036.0,...,1230.0,1083.5,1107.0,1143.5,1076.5,1111.5,1648.0,1415.0,1318.5,1385.0
1,2,1022.0,1009.5,1028.0,1238.0,1003.0,1045.5,1073.5,1114.0,1071.5,...,1187.0,1058.5,1090.0,1053.5,1137.0,1111.5,1740.0,1298.5,1420.0,2081.5
2,3,1006.0,1028.0,1021.5,1045.5,1007.5,1034.5,1064.0,1076.5,1034.5,...,1536.5,1148.5,1165.0,1138.5,1276.5,1150.0,2773.5,1518.5,1451.5,2070.0
3,4,1208.0,1012.5,1032.5,1026.5,998.5,1078.0,1061.0,1014.0,1001.5,...,1170.0,1141.5,1118.0,2183.5,1512.0,1866.5,1241.5,1643.5,1290.0,1163.5
4,5,1020.0,991.0,995.5,1012.5,997.0,995.5,992.5,1018.5,998.5,...,1680.0,1413.5,1263.5,1301.5,1060.0,1175.0,1217.0,1261.5,1528.5,1401.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,1126.5,1140.5,1351.5,1122.0,1101.5,1268.5,1548.5,1116.0,1095.5,...,1441.5,1347.0,1395.0,2976.5,1676.5,3141.5,1523.5,1515.0,1290.0,1147.0
996,997,1028.0,1020.0,990.5,1004.5,1007.5,1117.5,1033.0,1129.5,1040.5,...,1131.5,1065.0,1083.5,1068.0,1108.5,1126.5,1362.0,1205.0,1205.0,1421.5
997,998,1222.0,1167.5,1202.0,1157.5,1144.0,1166.0,1184.5,1178.0,1177.0,...,1433.5,1245.0,1190.0,1251.5,1450.0,1113.0,2428.0,1798.0,1736.5,5147.0
998,999,978.0,1093.5,1059.5,1027.0,1101.5,1097.0,1143.5,1076.5,1012.0,...,2020.0,1313.5,1493.5,1318.5,1260.0,1818.0,1348.5,1240.0,1150.0,1180.0
999,1000,1147.0,966.0,1223.5,1020.0,1036.0,952.0,1019.0,1064.0,1017.5,...,1158.5,1313.5,1298.5,1461.5,1207.0,1258.0,1183.5,1396.5,1356.5,1216.5

In [37]:
a = df.iloc[:, 1:51]
m = min(a.iloc[0,:])
bg = a.iloc[0,:]-m
df.iloc[0, 1:51] = bg
df.iloc[0, 1:51]

CD8a            28.50
CD4             15.50
CD25            34.50
CD27            31.50
CD28             0.00
CD45            25.00
CD69            22.00
CD45RA          41.00
CD38            47.00
CD20            11.00
CD57            17.00
CD62P           42.00
CD68            17.00
CD74            21.75
CD83            21.50
CD89             0.00
CD96            27.00
CD103           15.50
CD108           50.50
CD116           23.50
CD122           12.50
CD130           25.00
CD136           31.50
CD141           30.00
CD148           21.50
CD155           25.00
CD162           33.00
CD169           12.50
CD178           36.00
CD186           21.50
CD196           91.00
CD203c          11.00
CD212           29.50
CD223           22.00
CD235a          42.50
CD253           15.50
CD262            8.00
CD272           34.50
CD279           30.00
CD286           17.00
CD300c          66.00
CD309           36.00
CD321           31.50
CD329           18.50
CD340           47.00
CD360           33.00
CD370           48.50
EGF Receptor    33.00
HLA-DR          31.50
SSEA-4          31.50
Name: 0, dtype: float64

In [48]:
# subtracting by min value per batch per row
col_count = [50, 50, 50, 50, 50, 50, 21, 50, 50, 44]

col_start = 1
col_end = 1
nrows = len(df)
for x in range(len(col_count)):
    col_end += col_count[x]
    for y in range(nrows):
        df_part = df.iloc[:, col_start:col_end]
        row_min = min(df_part.iloc[y,:])
        row_bg_rem = df_part.iloc[y,:]-row_min
        df.iloc[y, col_start:col_end] = row_bg_rem
    col_start += col_count[x]

KeyboardInterrupt:

In [40]:
# subtracting by harmonic avg value per batch per row

def harmean(nums):
    # nums = list of values
    n = len(nums)
    
    sub = [0] * n
    for i in range(n):
        sub[i] = 1/nums[i]
    
    mean = n/sum(sub)
    
    return mean

col_count = [50, 50, 50, 50, 50, 50, 21, 50, 50, 44]

col_start = 1
col_end = 1
nrows = len(df)
for x in range(len(col_count)):
    col_end += col_count[x]
    for y in range(nrows):
        df_part = df.iloc[:, col_start:col_end]
        bg_value = harmean(df_part.iloc[y,:])
        row_bg_rem = df_part.iloc[y,:]-bg_value
        for z in range(len(row_bg_rem)):
            if row_bg_rem[z] < 0:
                row_bg_rem[z] = 0
        #print(bg_value)
        #print(row_bg_rem)
        df.iloc[y, col_start:col_end] = row_bg_rem
    col_start += col_count[x]

In [41]:
print(bg_value)
df.iloc[999, 421:465]

1311.603481541607

JNK                0.000000
PYCARD             0.000000
caspase 1        229.896518
STING              0.000000
TAPBP              0.000000
TAP1               0.000000
LC3              453.396518
LGMN               0.000000
c-MAF              0.000000
ZAP-70             0.000000
LAT                0.000000
SLP76              0.000000
VAV3             353.396518
NOTCH3           894.896518
T-bet            157.896518
RUNX3              0.000000
Gata3              0.000000
MEK1             289.896518
PAK1              18.396518
CREB               0.000000
Pho-Lck            0.000000
p47phox          278.396518
BCR              115.396518
BLNK             114.896518
EIF2S1             0.000000
Rac1             346.896518
SHIP1           1248.396518
Lyn               39.896518
p27/Kip1           0.000000
Pho-BTK            0.000000
GAB2               0.000000
Cyclin D1/D2       0.000000
Fyn                0.000000
GATA1              0.000000
Pho-BAD            0.000000
ARF6               0.000000
cofilin            1.896518
Cathepsin B        0.000000
NFAT             149.896518
IkB-alpha          0.000000
TBK1               0.000000
SHP2               0.000000
NOL3              84.896518
ROCK1             44.896518
Name: 999, dtype: float64

In [42]:
df.to_excel('Final_Combined_BatchEffect.xlsx')

In [48]:
dir = 'C:/Users/jesse/OneDrive/Documents/Multiplex Lab/Data/Pseudo-cells_preprocess.xlsx'

df_old = pd.read_excel(dir)

In [49]:
len(df_old.columns)-1

29

In [50]:
nrow = len(df_old)
ncol = len(df_old.columns)-1
df = df_old.iloc[:, 1:(ncol+1)]
df

,Protein 1,Protein 2,Protein 3,Protein 4,Protein 5,Protein 6,Protein 7,Protein 8,Protein 9,Protein 10,...,Protein 22,Protein 23,Protein 24,Protein 25,Protein 26,Protein 27,Protein 28,Protein 29,Protein 30,Protein 31
0,495,292,349,287,339,299,339,301,327,270,...,384,354,304,285,332,314,292,296,464,295
1,460,293,315,282,301,288,316,319,303,251,...,442,329,296,359,289,306,314,330,456,319
2,414,324,295,285,298,311,355,341,302,272,...,399,354,360,328,289,304,306,281,462,379
3,501,293,281,281,322,285,363,316,317,286,...,389,331,509,349,265,294,323,323,461,310
4,511,271,320,320,325,344,312,345,325,327,...,492,327,289,372,332,321,346,303,550,484
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48395,309,262,255,281,293,286,261,283,286,275,...,297,280,287,288,277,288,301,276,312,277
48396,248,282,287,268,300,273,285,274,279,268,...,268,288,302,289,271,284,339,257,272,282
48397,330,297,275,270,278,260,275,287,288,287,...,290,294,261,282,271,278,299,258,317,284
48398,319,268,251,278,295,270,280,278,274,274,...,272,281,316,280,272,271,264,255,317,309
48399,269,268,251,278,295,270,267,269,274,266,...,276,281,316,280,278,263,278,289,317,262

In [51]:
for x in range(ncol):
    bg = np.percentile(df.iloc[:, x], 75)
    for y in range(nrow):
        old_num = df.iloc[y, x]
        new_num = old_num - bg
        if new_num < 0:
            df.iloc[y, x] = 0
        else:
            df.iloc[y, x] = new_num

df_bg = df
df_bg

,Protein 1,Protein 2,Protein 3,Protein 4,Protein 5,Protein 6,Protein 7,Protein 8,Protein 9,Protein 10,...,Protein 22,Protein 23,Protein 24,Protein 25,Protein 26,Protein 27,Protein 28,Protein 29,Protein 30,Protein 31
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48395,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48396,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48397,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48398,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48399,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [52]:
drop = []
for x in range(nrow):
    if df_bg.iloc[x, :].any() == 0:
        drop.append(x)
df_drop = df_bg.drop(drop)
len(drop)

9068

In [53]:
from sklearn.preprocessing import normalize

colnames = df_drop.columns

# log normalize per cell
df_cellnorm = pd.DataFrame(normalize(df_drop, axis=1), columns=colnames)
# log2(x+1)
df_celllognorm = np.log2(df_cellnorm+1)

In [57]:
nrow_new = nrow-len(drop)

for x in range(nrow_new):
    for y in range(ncol):
        if df_celllognorm.iloc[x, y] < .5:
            df_celllognorm.iloc[x, y] = 0
        else:
            pass

In [61]:
df_celllognorm.to_excel('C:/Users/jesse/OneDrive/Documents/Multiplex Lab/Data/Intensities_Filtered50.xlsx')